### ISSUE TITLE
Discord.py commands

### ISSUE THREAD

**Issue by oolio151** [MyerFire/hypixelaPY#4]
I was using this with discord.py, and when I put the code outside of a discord command, it works fine, but the moment it goes inside a discord command, it throws errors. 
![image](https://user-images.githubusercontent.com/97859173/155404644-b453944c-0488-4c8c-b246-d65d596cf39b.png)
This works^
![image](https://user-images.githubusercontent.com/97859173/155404719-6c8b2da2-97d7-4397-a5eb-43c413b42a68.png)
But this does not^
Anyone know what is the problem?

**Comment by ernieIzde8ski** [comment]
1. Giving the exact error (as text) is helpful
2. Why are you getting the current event loop inside an async function? You know you can just await the function calls then and there, right?
3. Why are you creating a nested function if you're just gonna call it anyways?
4. It's probably better to create the `Hypixel` class outside of the function, seeing as you're going to call it more  than once.
5. `pass` is a thing -- I'd recommend reading [these docs](https://docs.python.org/3/), and maybe [these docs in particular](https://docs.python.org/3/library/asyncio.html#module-asyncio) for working with async
