### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by Kejax** [MyerFire/hypixelaPY#5]
Hi Myer, I‘m following hypixelaPY since about 1 year and a few months, and I‘m curios if it is still maintained. The other question is, if you would accept help. I‘ve tried doing a Hypixel Library by myself after no functions were added for a long time, but I gave it up. So I viewed the code behind hypixelaPY even more then before and I would really like to help you with it. ;-)

Greetings from germany,
Kejax
(Kejax#9429 on Discord)

**Comment by myerDOT** [comment]
It is not actively maintained anymore due to my lack of interest in Hypixel and Minecraft in general, but if you would like to help by adding more games to the wrapper, that will be accepted.
